# Generated by Django 4.2.1 on 2023-06-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="phone_number",
            new_name="phone",
        ),
        migrations.AddField(
            model_name="client",
            name="mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
