# Generated by Django 4.2.1 on 2023-06-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0002_rename_phone_number_client_phone_client_mobile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="associated_team_member",
            new_name="sales_contact",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="associated_team_member",
            new_name="sales_contact",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="associated_team_member",
            new_name="sales_contact",
        ),
    ]
