# Generated by Django 4.2.1 on 2023-06-29 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0007_alter_userwithrole_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="payment_due_date",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="signed",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="event",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="event",
            name="finished",
        ),
        migrations.RemoveField(
            model_name="event",
            name="number_of_guests",
        ),
        migrations.RemoveField(
            model_name="event",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="contract",
            name="date_created",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contract",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="payment_due",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Contract signed?"),
        ),
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="date_created",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="event",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="event",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Event completed?"),
        ),
    ]
