# Generated by Django 4.2.1 on 2023-06-29 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("CRM", "0006_alter_event_contract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwithrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
