# Generated by Django 4.2.1 on 2023-06-29 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("CRM", "0009_alter_event_sales_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="sales_contact",
        ),
        migrations.AddField(
            model_name="event",
            name="support_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
